version: '3.7'
services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB = phrases
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = root
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  frontend:
    build: ./frontend/quote-gen-ui
    ports:
      - "80:80"