version: '3.7'
services:
  postgresql:
    image: "postgres:14"
    container_name: postgresql
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=phrases
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8081:8081"
    environment:
      - DB_SERVER=postgresql
      - DB_PORT=5432
      - POSTGRES_DB=phrases
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    depends_on:
      - postgresql
  frontend:
    build: ./frontend/frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres-data:
    driver: local